# Generated by Django 2.1.15 on 2020-06-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=10)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
