# Generated by Django 2.1.15 on 2020-06-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20200620_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='title',
            new_name='name',
        ),
    ]
