# Generated by Django 3.1.1 on 2020-09-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_auto_20200906_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinventory',
            old_name='model',
            new_name='model1',
        ),
    ]
