# Generated by Django 3.1.1 on 2020-09-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_auto_20200906_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinventory',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='salesorder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='scannum1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='scannum2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='scannum3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='scannum4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='scantype1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='scantype2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='scantype3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='scantype4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
